version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: rental_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rentaldatabase
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d rentaldatabase']
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: api_observabilidade
    command: sh -c "npx prisma db push && npm run start"
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'postgresql://user:password@db:5432/rentaldatabase?schema=public'
    depends_on:
      db:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - '3001:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  pgdata:
  grafana-storage:
